use_frameworks!

source 'https://github.com/dcwy1130/PrivatePods.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'ModuleB_Example' do
  pod 'ModuleB', :path => '../'

  target 'ModuleB_Tests' do
    inherit! :search_paths

    
  end
end
